### ISSUE TITLE
Overwrite the old installed software version

### ISSUE THREAD

**Issue by santos-lucasm** [SamuelPossamai/spaceship-control#15]
**Describe the bug**
Following the README to install the software ( typing _pip3 install . --user_ ), it gets a segmentation fault.

**To Reproduce**
1. _git pull_ command on the base folder of the already installed project.
2. _pip3 install . --user_

**Expected behavior**
A successful installation.

**Desktop (please complete the following information):**
- OS: Ubuntu
- Version: 18.04.4 LTS

**Additional context**
I had installed the previous version of the project.
When I _git pull_ to the newer version, typing _spaceshipcontrol_ to start the software, would start the older version but that's ok.
Following the README to install the software ( typing _pip3 install . --user_ ), it gets a segmentation fault.

**Comment by SamuelPossamai** [comment]
Can you change 'PyQt5>=5.13.2' to 'PyQt5==5.13.2' inside 'requirements.txt' file? It is working for me using Manjaro and some time ago I had a problem updating PyQt5 on ubuntu.

**Comment by santos-lucasm** [comment]
PyQt5 version is already defined to be 5.13.2, but the problem persists.

**Comment by SamuelPossamai** [comment]
Can you show the complete error message?

**Comment by santos-lucasm** [comment]
It shows sucessful installation, and then shows the Segmentation fault issue.
If I try to start the software afterwards it shows the error message of the closed issue #16 
![bug_screen2](https://user-images.githubusercontent.com/21278257/79455012-9a758f00-7fc2-11ea-9799-dec0d8348ec6.png)

**Comment by SamuelPossamai** [comment]
So you're trying to install the software using python3.3?

**Comment by santos-lucasm** [comment]
here python3 is on version 3.6.9

**Comment by SamuelPossamai** [comment]
It would help to use gdb on pip and get  the traceback when the error occur, if it's too much trouble for you, I will eventually test it on ubuntu and try to figure out what's causing the problem.

**Comment by SamuelPossamai** [comment]
It seems that the installation happens even if it occur this segmentation fault, so I will close this issue for now.
