### ISSUE TITLE
SimpleQueue import problem on python version >= 3.3

### ISSUE THREAD

**Issue by santos-lucasm** [SamuelPossamai/spaceship-control#16]
**Describe the bug**
Following the README to run the software ( typing _python3 -m src.main_ ), it cannot import SimpleQueue from queue. 

**To Reproduce**

1. git pull
2. python3 -m src.main

**Expected behavior**
A successful installation of the software.

**Screenshots**
![bug_screenshot](https://user-images.githubusercontent.com/21278257/79343573-ea8e1c00-7f04-11ea-8a28-27fd0ab0b8ca.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04.4 LTS

**Additional context**
I actually found what the problem can be. My python3 version is 3.6.9, if the software uses the python3.2 or older, the SimpleQueue is located in another place.
You can see a explanation [here](https://stackoverflow.com/questions/32757362/python3-error-cannot-import-name-simplequeue)

**Comment by SamuelPossamai** [comment]
According to the link I 'multiprocessing.SimpleQueue' turned into 'multiprocessing.queues.SimpleQueue', but 'queue.SimpleQueue' is used in the program and they seem incompatible.

So I decided that this issue will be closed for now and support for old versions of Python 3 will not be supported.

**Comment by SamuelPossamai** [comment]
When I read the issue for the first time I thought your python version was 3.2 because of this comment "if the software uses the python3.2 or older", but now I see this problem happens with 3.6.
